### ISSUE TITLE
Faster GPU question?

### ISSUE THREAD

**Issue by zelenooki87** [ArcticHare105/S3Diff#16]
Will a more powerful GPU like the A100 offer advantages over an RTX 3090 for upscaling a large image gallery, particularly regarding tiling and overall quality for higher-resolution images? I'm currently able to upscale images up to 5-6MP on my RTX 3090, but the process is slow, and I'm wondering if the A100 would provide both a speed boost and potentially better results for larger images. Does the tiling process function identically on both GPUs, maintaining the same pixel-level operations regardless of input or hardware resolution? How significant a performance improvement could I expect with the A100? 
I might pay for a cloud GPU for this purpose.

Thank you!

**Comment by ArcticHare105** [comment]
The NVIDIA A100 offers significant speed and efficiency improvements over the RTX 3090 for upscaling large images due to its higher processing power and memory capacity. This results in faster processing and potentially better handling of larger images without extensive tiling. The quality of results should remain consistent across both GPUs since the model itself doesn't change; however, the A100 can process more efficiently, potentially allowing for higher settings that improve outcomes.

**Comment by zelenooki87** [comment]
Does this mean the automatic tiling function adapts to available VRAM rather than the image dimensions? I thought the model had a fixed tiling technique? If the tiling technique is fixed, then the tile overlap seams will be noticeable, and the effective output would be the same with any GPU capable of processing the image. This would be my first cloud-rented GPU, so if the only gain is speed, I might not want to rush into it and spend the money. :)

**Comment by ArcticHare105** [comment]
Yes, the tiling technique is fixed, but more VRAM allows you to use larger tile sizes, which can help mitigate tiling issues. If you use the same tile size and tile overlap, there won't be any difference between GPUs.
