### ISSUE TITLE
can put the pretrained model into huggingface?

### ISSUE THREAD

**Issue by dongdk** [ArcticHare105/S3Diff#3]

**Comment by ArcticHare105** [comment]
@dongdk We have created a model in huggingface, refer to [here](https://huggingface.co/zhangap/S3Diff).

**Comment by dongdk** [comment]
thanks a lot

**Comment by NielsRogge** [comment]
Thanks a lot @ArcticHare105, nice to see it being linked to https://huggingface.co/papers/2409.17058.

Would be great to mention it in the README of this repo. This is all it takes to download it:

```python
from huggingface_hub import hf_hub_download

filepath = hf_hub_download(filepath="zhangap/S3Diff", filename="de_net.pth")
```
This could also be used inside your scripts so that people don't need to manually download the checkpoints first. See https://huggingface.co/docs/huggingface_hub/en/guides/download for details.

Btw, downloads currently aren't tracked for your model, that's because the repo does not contain a config.json or config.yaml, see here for details on how to enable them: https://huggingface.co/docs/hub/models-download-stats
